export const QUIZ_QUESTIONS = [
  // ── MÉTÉOROLOGIE ──────────────────────────────────────────────────────────
  {
    category:'Météorologie', phase:'p1',
    question_fr:'À quelle vitesse maximale du vent peut-on effectuer des vols solo en P1?',
    question_en:'What is the maximum wind speed for solo P1 flights?',
    opt_a_fr:'10 km/h', opt_b_fr:'20 km/h', opt_c_fr:'30 km/h', opt_d_fr:'40 km/h',
    opt_a_en:'10 km/h', opt_b_en:'20 km/h', opt_c_en:'30 km/h', opt_d_en:'40 km/h',
    correct:'B',
    explain_fr:'Les vols P1 s\'effectuent dans des vents de 0 à 20 km/h maximum.',
    explain_en:'P1 flights are conducted in winds from 0 to 20 km/h maximum.',
  },
  {
    category:'Météorologie', phase:'p1',
    question_fr:'La règle des rafales pour voler en sécurité est que les rafales ne doivent pas dépasser de plus de __ % le vent moyen.',
    question_en:'The gust rule for safe flying is that gusts must not exceed the average wind by more than __% .',
    opt_a_fr:'25%', opt_b_fr:'50%', opt_c_fr:'75%', opt_d_fr:'100%',
    opt_a_en:'25%', opt_b_en:'50%', opt_c_en:'75%', opt_d_en:'100%',
    correct:'B',
    explain_fr:'Exemple: vent moyen 10 km/h → rafales max 15 km/h (50% de plus).',
    explain_en:'Example: average wind 10 km/h → max gusts 15 km/h (50% more).',
  },
  {
    category:'Météorologie', phase:'p1',
    question_fr:'Les thermiques se forment généralement à quelle période de la journée?',
    question_en:'Thermals generally form at what time of day?',
    opt_a_fr:'Tôt le matin (6h–9h)', opt_b_fr:'En fin de matinée et l\'après-midi (10h–17h)',
    opt_c_fr:'La nuit', opt_d_fr:'Au coucher du soleil uniquement',
    opt_a_en:'Early morning (6am–9am)', opt_b_en:'Late morning and afternoon (10am–5pm)',
    opt_c_en:'At night', opt_d_en:'At sunset only',
    correct:'B',
    explain_fr:'Le soleil chauffe le sol et crée des bulles d\'air chaud (thermiques) surtout en fin de matinée et l\'après-midi.',
    explain_en:'The sun heats the ground creating thermal bubbles especially in late morning and afternoon.',
  },
  {
    category:'Météorologie', phase:'p1',
    question_fr:'Qu\'est-ce que l\'effet Venturi?',
    question_en:'What is the Venturi effect?',
    opt_a_fr:'Le refroidissement de l\'air en altitude', opt_b_fr:'L\'accélération du vent dans un couloir ou col montagneux',
    opt_c_fr:'La rotation de la Terre qui dévie les vents', opt_d_fr:'La formation de nuages par convection',
    opt_a_en:'Cooling of air at altitude', opt_b_en:'Acceleration of wind through a mountain pass or corridor',
    opt_c_en:'Earth\'s rotation deflecting winds', opt_d_en:'Cloud formation by convection',
    correct:'B',
    explain_fr:'L\'effet Venturi comprime et accélère l\'air dans les passages étroits, créant des rafales dangereuses.',
    explain_en:'The Venturi effect compresses and accelerates air through narrow passages, creating dangerous gusts.',
  },
  {
    category:'Météorologie', phase:'p1',
    question_fr:'Quel type de nuage indique la présence de thermiques actifs?',
    question_en:'Which cloud type indicates active thermals?',
    opt_a_fr:'Stratus', opt_b_fr:'Cirrus', opt_c_fr:'Cumulus', opt_d_fr:'Nimbostratus',
    opt_a_en:'Stratus', opt_b_en:'Cirrus', opt_c_en:'Cumulus', opt_d_en:'Nimbostratus',
    correct:'C',
    explain_fr:'Les cumulus à base plate sont des marqueurs visibles de thermiques.',
    explain_en:'Flat-based cumulus clouds are visible markers of thermals.',
  },
  {
    category:'Météorologie', phase:'p1',
    question_fr:'Le gradient thermique sec adiabatique (DALR) est d\'environ:',
    question_en:'The dry adiabatic lapse rate (DALR) is approximately:',
    opt_a_fr:'1°C / 100m', opt_b_fr:'3°C / 100m', opt_c_fr:'5°C / 100m', opt_d_fr:'10°C / 100m',
    opt_a_en:'1°C / 100m', opt_b_en:'3°C / 100m', opt_c_en:'5°C / 100m', opt_d_en:'10°C / 100m',
    correct:'A',
    explain_fr:'L\'air sec se refroidit d\'environ 1°C tous les 100 mètres d\'ascension.',
    explain_en:'Dry air cools approximately 1°C for every 100 meters of ascent.',
  },
  {
    category:'Météorologie', phase:'p1',
    question_fr:'Quelle est la direction du vent acceptable pour le décollage NE à Mont Yamaska?',
    question_en:'What wind direction is acceptable for the NE launch at Mont Yamaska?',
    opt_a_fr:'S à SW', opt_b_fr:'NNE à NNW', opt_c_fr:'E à SE', opt_d_fr:'W à NW uniquement',
    opt_a_en:'S to SW', opt_b_en:'NNE to NNW', opt_c_en:'E to SE', opt_d_en:'W to NW only',
    correct:'B',
    explain_fr:'Le décollage NE accepte les vents de NNE à NNW, perpendiculaires à la pente.',
    explain_en:'The NE launch accepts winds from NNE to NNW, perpendicular to the slope.',
  },
  {
    category:'Météorologie', phase:'p2',
    question_fr:'Un cumulonimbus (Cb) représente quel risque pour les parapentistes?',
    question_en:'A cumulonimbus (Cb) represents what risk for paraglider pilots?',
    opt_a_fr:'Aucun risque si on vole en dessous', opt_b_fr:'Risque de pluie uniquement',
    opt_c_fr:'Turbulences violentes, aspiration, foudre — danger mortel', opt_d_fr:'Brouillard au sol seulement',
    opt_a_en:'No risk if flying below', opt_b_en:'Rain risk only',
    opt_c_en:'Violent turbulence, suction, lightning — mortal danger', opt_d_en:'Ground fog only',
    correct:'C',
    explain_fr:'Les Cb génèrent des courants ascendants et descendants extrêmes, de la foudre et peuvent aspirer l\'aile dans le nuage.',
    explain_en:'Cb clouds generate extreme up and downdrafts, lightning, and can suck the glider into the cloud.',
  },
  {
    category:'Météorologie', phase:'p2',
    question_fr:'Qu\'est-ce qu\'une brise de vallée?',
    question_en:'What is a valley breeze?',
    opt_a_fr:'Vent constant de 20 km/h dans les vallées', opt_b_fr:'Vent ascendant le long des pentes chauffées par le soleil le matin',
    opt_c_fr:'Vent descendant la nuit', opt_d_fr:'Turbulence mécanique derrière une montagne',
    opt_a_en:'Constant 20 km/h wind in valleys', opt_b_en:'Upslope wind along sun-heated slopes in the morning',
    opt_c_en:'Downslope wind at night', opt_d_en:'Mechanical turbulence behind a mountain',
    correct:'B',
    explain_fr:'La brise de vallée monte les pentes le jour quand le sol se réchauffe.',
    explain_en:'The valley breeze flows upslope during the day as the ground warms.',
  },
  {
    category:'Météorologie', phase:'p2',
    question_fr:'Le vent de rotor se forme:',
    question_en:'Rotor winds form:',
    opt_a_fr:'Au sommet d\'une montagne', opt_b_fr:'Sous le vent d\'un obstacle, dans la zone d\'ombre au vent',
    opt_c_fr:'Au-dessus des nuages', opt_d_fr:'En présence de brouillard',
    opt_a_en:'At the top of a mountain', opt_b_en:'Downwind of an obstacle, in the wind shadow zone',
    opt_c_en:'Above the clouds', opt_d_en:'In the presence of fog',
    correct:'B',
    explain_fr:'Le rotor est une turbulence rotationnelle qui se forme sous le vent des obstacles (arbres, collines, bâtiments).',
    explain_en:'Rotor is rotational turbulence forming downwind of obstacles (trees, hills, buildings).',
  },

  // ── AÉRODYNAMIQUE ─────────────────────────────────────────────────────────
  {
    category:'Aérodynamique', phase:'p1',
    question_fr:'Qu\'est-ce que l\'angle d\'attaque?',
    question_en:'What is the angle of attack?',
    opt_a_fr:'L\'angle entre l\'aile et le vent relatif', opt_b_fr:'L\'angle de la pente de descente',
    opt_c_fr:'L\'angle entre les suspentes et le sol', opt_d_fr:'L\'angle de virage',
    opt_a_en:'The angle between the wing and the relative wind', opt_b_en:'The angle of the descent slope',
    opt_c_en:'The angle between the lines and the ground', opt_d_en:'The turn angle',
    correct:'A',
    explain_fr:'L\'angle d\'attaque est l\'angle formé entre le profil de l\'aile et le vent relatif qui la frappe.',
    explain_en:'The angle of attack is the angle formed between the wing profile and the relative wind striking it.',
  },
  {
    category:'Aérodynamique', phase:'p1',
    question_fr:'Quelle est la finesse typique d\'un parapente de niveau débutant?',
    question_en:'What is the typical glide ratio of a beginner-level paraglider?',
    opt_a_fr:'3:1', opt_b_fr:'5:1', opt_c_fr:'8:1', opt_d_fr:'12:1',
    opt_a_en:'3:1', opt_b_en:'5:1', opt_c_en:'8:1', opt_d_en:'12:1',
    correct:'C',
    explain_fr:'Un parapente EN-A typique a une finesse de 7–9:1, soit environ 8 mètres horizontalement pour 1 mètre de descente.',
    explain_en:'A typical EN-A paraglider has a glide ratio of 7–9:1, approximately 8 meters forward for every 1 meter down.',
  },
  {
    category:'Aérodynamique', phase:'p1',
    question_fr:'Qu\'est-ce qu\'un décrochage (stall)?',
    question_en:'What is a stall?',
    opt_a_fr:'L\'aile s\'ouvre mal au gonflage', opt_b_fr:'L\'angle d\'attaque devient trop grand, la portance est perdue',
    opt_c_fr:'Le pilote perd le contrôle en virage', opt_d_fr:'L\'aile se ferme par manque de vent',
    opt_a_en:'The glider opens poorly during inflation', opt_b_en:'The angle of attack becomes too large, lift is lost',
    opt_c_en:'The pilot loses control in a turn', opt_d_en:'The glider collapses due to lack of wind',
    correct:'B',
    explain_fr:'Le décrochage survient quand l\'angle d\'attaque dépasse l\'angle critique, causant la séparation du flux d\'air.',
    explain_en:'A stall occurs when the angle of attack exceeds the critical angle, causing airflow separation.',
  },
  {
    category:'Aérodynamique', phase:'p1',
    question_fr:'Pour tourner à droite en parapente, le pilote:',
    question_en:'To turn right in paragliding, the pilot:',
    opt_a_fr:'Incline le corps vers la droite uniquement', opt_b_fr:'Tire la commande droite vers le bas',
    opt_c_fr:'Tire la commande gauche vers le bas', opt_d_fr:'Pousse le frein droit vers le haut',
    opt_a_en:'Leans their body right only', opt_b_en:'Pulls the right brake down',
    opt_c_en:'Pulls the left brake down', opt_d_en:'Pushes the right brake up',
    correct:'B',
    explain_fr:'Tirer le frein droit ralentit l\'aile droite, créant un différentiel de vitesse qui fait tourner l\'aile vers la droite.',
    explain_en:'Pulling the right brake slows the right side of the glider, creating a speed differential that turns it right.',
  },
  {
    category:'Aérodynamique', phase:'p1',
    question_fr:'Qu\'est-ce que la polaire des vitesses?',
    question_en:'What is the speed polar (polar curve)?',
    opt_a_fr:'La liste des vitesses autorisées en airspace', opt_b_fr:'Un graphique liant la vitesse horizontale et la vitesse de chute',
    opt_c_fr:'La vitesse maximale de l\'aile', opt_d_fr:'La différence entre vitesse sol et vitesse air',
    opt_a_en:'The list of authorized speeds in airspace', opt_b_en:'A graph linking horizontal speed and sink rate',
    opt_c_en:'The maximum speed of the glider', opt_d_en:'The difference between ground speed and airspeed',
    correct:'B',
    explain_fr:'La polaire des vitesses montre la performance de l\'aile: finesse max, vitesse de chute min, vitesse max.',
    explain_en:'The speed polar shows glider performance: max glide, min sink, max speed.',
  },
  {
    category:'Aérodynamique', phase:'p2',
    question_fr:'Qu\'est-ce qu\'une fermeture frontale?',
    question_en:'What is a frontal collapse?',
    opt_a_fr:'La fermeture du bord de fuite de l\'aile', opt_b_fr:'L\'effondrement du bord d\'attaque sur toute la largeur',
    opt_c_fr:'La fermeture asymétrique d\'un côté de l\'aile', opt_d_fr:'L\'atterrissage d\'urgence',
    opt_a_en:'Closing of the trailing edge', opt_b_en:'Collapse of the leading edge across the full span',
    opt_c_en:'Asymmetric collapse on one side', opt_d_en:'Emergency landing',
    correct:'B',
    explain_fr:'La fermeture frontale survient quand la pression interne est insuffisante pour maintenir le bord d\'attaque ouvert.',
    explain_en:'A frontal collapse occurs when internal pressure is insufficient to keep the leading edge open.',
  },
  {
    category:'Aérodynamique', phase:'p2',
    question_fr:'Lors d\'une fermeture asymétrique, quelle est la première action du pilote?',
    question_en:'During an asymmetric collapse, what is the pilot\'s first action?',
    opt_a_fr:'Sortir les petites oreilles', opt_b_fr:'Déployer le parachute de secours immédiatement',
    opt_c_fr:'Contre-braker pour stopper la rotation et maintenir la direction', opt_d_fr:'Mettre l\'accélérateur',
    opt_a_en:'Deploy big ears', opt_b_en:'Deploy the reserve parachute immediately',
    opt_c_en:'Counter-brake to stop rotation and maintain heading', opt_d_en:'Apply speed bar',
    correct:'C',
    explain_fr:'Contre-braker du côté de l\'aile non effondrée arrête la rotation. L\'aile réouvre généralement spontanément.',
    explain_en:'Counter-braking on the open side stops the rotation. The glider usually reopens spontaneously.',
  },
  {
    category:'Aérodynamique', phase:'p2',
    question_fr:'La vrille (cravate) se produit quand:',
    question_en:'A cravat occurs when:',
    opt_a_fr:'Le pilote décroche l\'aile intentionnellement', opt_b_fr:'Une suspente ou le bord d\'attaque s\'accroche sur le bout d\'aile lors d\'une fermeture',
    opt_c_fr:'L\'aile tourne trop vite', opt_d_fr:'Le parachute de secours s\'emmêle',
    opt_a_en:'The pilot intentionally stalls the glider', opt_b_en:'A line or leading edge catches on the wingtip during a collapse',
    opt_c_en:'The glider rotates too fast', opt_d_en:'The reserve parachute tangles',
    correct:'B',
    explain_fr:'Une cravate peut nécessiter le déploiement du secours si elle ne se résout pas.',
    explain_en:'A cravat may require reserve deployment if it does not resolve.',
  },

  // ── MATÉRIEL ───────────────────────────────────────────────────────────────
  {
    category:'Matériel', phase:'p1',
    question_fr:'Que signifie la certification EN-A pour un parapente?',
    question_en:'What does EN-A certification mean for a paraglider?',
    opt_a_fr:'Aile de compétition haute performance', opt_b_fr:'Aile très stable, auto-stable, idéale pour débutants',
    opt_c_fr:'Aile réservée aux instructeurs', opt_d_fr:'Aile pour acrobaties',
    opt_a_en:'High performance competition glider', opt_b_en:'Very stable, self-recovering glider, ideal for beginners',
    opt_c_en:'Glider reserved for instructors', opt_d_en:'Glider for aerobatics',
    correct:'B',
    explain_fr:'Les ailes EN-A sont conçues pour être très indulgentes et se rétablir automatiquement des incidents.',
    explain_en:'EN-A gliders are designed to be very forgiving and self-recover from incidents.',
  },
  {
    category:'Matériel', phase:'p1',
    question_fr:'À quelle fréquence le parachute de secours doit-il être repli (repack) au Canada?',
    question_en:'How often must the reserve parachute be repacked in Canada?',
    opt_a_fr:'Tous les 5 ans', opt_b_fr:'Tous les 2 ans maximum', opt_c_fr:'Tous les 10 ans', opt_d_fr:'Jamais, sauf après utilisation',
    opt_a_en:'Every 5 years', opt_b_en:'Every 2 years maximum', opt_c_en:'Every 10 years', opt_d_en:'Never, except after deployment',
    correct:'B',
    explain_fr:'Summit Paragliding recommande un repli tous les 1–2 ans pour garantir la fiabilité et vérifier l\'état du tissu.',
    explain_en:'Summit Paragliding recommends repacking every 1–2 years to ensure reliability and check fabric condition.',
  },
  {
    category:'Matériel', phase:'p1',
    question_fr:'La vérification ABCDE avant le vol correspond à:',
    question_en:'The pre-flight ABCDE check stands for:',
    opt_a_fr:'Aile, Baudrier, Casque, Direction, Équipement', opt_b_fr:'Attachements, Boucles, Commandes, Données météo, Exercices',
    opt_c_fr:'Aile, Baudrier, Commandes, Direction, Emergency plan',
    opt_d_fr:'Attitude, Brevet, Compétences, Décision, Environnement',
    opt_a_en:'Wing, Harness, Helmet, Direction, Equipment', opt_b_en:'Attachments, Buckles, Controls, Data weather, Exercises',
    opt_c_en:'Wing, Harness, Controls, Direction, Emergency plan',
    opt_d_en:'Attitude, License, Skills, Decision, Environment',
    correct:'C',
    explain_fr:'ABCDE: Aile (inspection), Baudrier (boucles), Commandes (freins libres), Direction (dégagée), Emergency (plan B).',
    explain_en:'ABCDE: Wing (inspection), Harness (buckles), Controls (brakes free), Direction (clear), Emergency (plan B).',
  },
  {
    category:'Matériel', phase:'p1',
    question_fr:'Le mousqueton qui relie les élévateurs à la sellette doit être:',
    question_en:'The carabiner connecting risers to the harness must be:',
    opt_a_fr:'Verrouillé et certifié', opt_b_fr:'N\'importe quel mousqueton d\'escalade', opt_c_fr:'Ouvert pour faciliter le dégagement', opt_d_fr:'En plastique pour être léger',
    opt_a_en:'Locked and certified', opt_b_en:'Any climbing carabiner', opt_c_en:'Open for easy release', opt_d_en:'Plastic to save weight',
    correct:'A',
    explain_fr:'Les mousquetons doivent être certifiés pour la charge et verrouillés avant chaque vol.',
    explain_en:'Carabiners must be certified for the load and locked before each flight.',
  },
  {
    category:'Matériel', phase:'p1',
    question_fr:'Qu\'est-ce que la charge alaire (wing loading)?',
    question_en:'What is wing loading?',
    opt_a_fr:'Le poids de l\'aile uniquement', opt_b_fr:'Le poids total (AUW) divisé par la surface de l\'aile',
    opt_c_fr:'La surface projetée de l\'aile', opt_d_fr:'La résistance des suspentes en kg',
    opt_a_en:'The weight of the glider only', opt_b_en:'Total weight (AUW) divided by wing area',
    opt_c_en:'The projected area of the glider', opt_d_en:'The line resistance in kg',
    correct:'B',
    explain_fr:'Charge alaire = AUW (kg) / surface à plat (m²). Typiquement 2.5–4.5 kg/m² pour un parapente.',
    explain_en:'Wing loading = AUW (kg) / flat area (m²). Typically 2.5–4.5 kg/m² for a paraglider.',
  },
  {
    category:'Matériel', phase:'p2',
    question_fr:'Qu\'est-ce que la surface projetée d\'une aile (projected area)?',
    question_en:'What is the projected area of a glider?',
    opt_a_fr:'La surface mesurée à plat, aile étendue', opt_b_fr:'La surface réelle de l\'aile en vol (vue du dessous)',
    opt_c_fr:'La surface des cellules fermées', opt_d_fr:'La surface équivalente d\'un cercle',
    opt_a_en:'Area measured flat with the glider spread out', opt_b_en:'The actual area of the glider in flight (seen from below)',
    opt_c_en:'The area of closed cells', opt_d_en:'The equivalent area of a circle',
    correct:'B',
    explain_fr:'La surface projetée est plus petite que la surface à plat car l\'aile est arquée en vol.',
    explain_en:'Projected area is smaller than flat area because the glider is arched in flight.',
  },
  {
    category:'Matériel', phase:'p2',
    question_fr:'La durée de vie typique recommandée d\'un parapente est:',
    question_en:'The typical recommended lifespan of a paraglider is:',
    opt_a_fr:'500 heures ou 10 ans', opt_b_fr:'200 heures ou 5 ans', opt_c_fr:'1000 heures seulement', opt_d_fr:'Illimitée si bien entretenue',
    opt_a_en:'500 hours or 10 years', opt_b_en:'200 hours or 5 years', opt_c_en:'1000 hours only', opt_d_en:'Unlimited if well maintained',
    correct:'A',
    explain_fr:'La plupart des fabricants recommandent une vérification complète à 500h et un remplacement après 10 ans.',
    explain_en:'Most manufacturers recommend a full inspection at 500h and replacement after 10 years.',
  },

  // ── RÉGLEMENTATION ────────────────────────────────────────────────────────
  {
    category:'Réglementation', phase:'p1',
    question_fr:'Au Canada, le parapente est réglementé par:',
    question_en:'In Canada, paragliding is regulated by:',
    opt_a_fr:'Parcs Canada', opt_b_fr:'Transport Canada — Règlement de l\'aviation canadien (RAC)',
    opt_c_fr:'La Croix-Rouge', opt_d_fr:'Les provinces uniquement',
    opt_a_en:'Parks Canada', opt_b_en:'Transport Canada — Canadian Aviation Regulations (CARs)',
    opt_c_en:'The Red Cross', opt_d_en:'Provinces only',
    correct:'B',
    explain_fr:'Le RAC de Transport Canada réglemente tous les aéronefs, incluant les parapentes (aéronefs ultralégers).',
    explain_en:'Transport Canada\'s CARs regulate all aircraft, including paragliders (ultralight aircraft).',
  },
  {
    category:'Réglementation', phase:'p1',
    question_fr:'Quel espace aérien est généralement disponible pour le parapente sans autorisation spéciale?',
    question_en:'Which airspace is generally available to paragliders without special authorization?',
    opt_a_fr:'Classe A', opt_b_fr:'Classe C', opt_c_fr:'Classe G (non contrôlé)', opt_d_fr:'Classe D',
    opt_a_en:'Class A', opt_b_en:'Class C', opt_c_en:'Class G (uncontrolled)', opt_d_en:'Class D',
    correct:'C',
    explain_fr:'L\'espace aérien de classe G (non contrôlé) est généralement accessible aux parapentistes.',
    explain_en:'Class G (uncontrolled) airspace is generally accessible to paragliders.',
  },
  {
    category:'Réglementation', phase:'p1',
    question_fr:'La règle de priorité en parapente: en cas de croisement face à face, les deux pilotes doivent:',
    question_en:'Right of way rule in paragliding: when two pilots approach head-on, both pilots must:',
    opt_a_fr:'Monter l\'un et descendre l\'autre', opt_b_fr:'Se déporter sur leur droite respective',
    opt_c_fr:'Le pilote le plus bas a priorité', opt_d_fr:'Le pilote qui monte a priorité',
    opt_a_en:'One go up and one go down', opt_b_en:'Each turn to their respective right',
    opt_c_en:'The lower pilot has priority', opt_d_en:'The climbing pilot has priority',
    correct:'B',
    explain_fr:'En cas de rencontre frontale, les deux pilotes se déportent vers leur droite, comme en navigation aérienne.',
    explain_en:'In a head-on encounter, both pilots turn right, as in air navigation.',
  },
  {
    category:'Réglementation', phase:'p1',
    question_fr:'Qui a la priorité entre un parapente et un planeur?',
    question_en:'Who has priority between a paraglider and a glider?',
    opt_a_fr:'Le parapente toujours', opt_b_fr:'Le planeur toujours',
    opt_c_fr:'Celui qui vole le plus bas', opt_d_fr:'Le parapente doit céder le passage au planeur non motorisé',
    opt_a_en:'The paraglider always', opt_b_en:'The glider always',
    opt_c_en:'Whichever is flying lower', opt_d_en:'The paraglider must yield to the non-motorized glider',
    correct:'D',
    explain_fr:'L\'ordre de priorité: ballons > planeurs > aéronefs remorqués > avions > hélicoptères > ULM/parapentes.',
    explain_en:'Priority order: balloons > gliders > towed aircraft > airplanes > helicopters > ULM/paragliders.',
  },
  {
    category:'Réglementation', phase:'p1',
    question_fr:'La certification HPAC/ACVL P1 permet de:',
    question_en:'The HPAC/ACVL P1 certification allows:',
    opt_a_fr:'Voler n\'importe où sans restriction', opt_b_fr:'Pratiquer des vols solo supervisés dans des conditions légères',
    opt_c_fr:'Effectuer des vols biplace comme pilote', opt_d_fr:'Former d\'autres pilotes',
    opt_a_en:'Fly anywhere without restriction', opt_b_en:'Perform solo flights supervised in light conditions',
    opt_c_en:'Perform tandem flights as pilot', opt_d_en:'Train other pilots',
    correct:'B',
    explain_fr:'P1 est le premier niveau — vol solo en conditions légères, idéalement avec supervision de l\'instructeur.',
    explain_en:'P1 is the first level — solo flight in light conditions, ideally with instructor supervision.',
  },
  {
    category:'Réglementation', phase:'p2',
    question_fr:'La hauteur minimale recommandée pour déployer le parachute de secours est:',
    question_en:'The minimum recommended height for deploying the reserve parachute is:',
    opt_a_fr:'Moins de 50m', opt_b_fr:'Entre 50m et 100m AGL', opt_c_fr:'Plus de 100m AGL', opt_d_fr:'Il n\'y a pas de hauteur minimale',
    opt_a_en:'Below 50m', opt_b_en:'Between 50m and 100m AGL', opt_c_en:'Over 100m AGL', opt_d_en:'There is no minimum height',
    correct:'C',
    explain_fr:'Le secours a besoin d\'au moins 100m pour s\'ouvrir complètement et ralentir la descente.',
    explain_en:'The reserve needs at least 100m to fully open and slow the descent.',
  },
  {
    category:'Réglementation', phase:'p2',
    question_fr:'Le vol de nuit en parapente est-il autorisé au Canada?',
    question_en:'Is night flying in paragliding authorized in Canada?',
    opt_a_fr:'Oui, sans restriction', opt_b_fr:'Oui, avec feux de position', opt_c_fr:'Non, le parapente est réservé aux vols de jour VMC', opt_d_fr:'Oui, après 23h seulement',
    opt_a_en:'Yes, without restriction', opt_b_en:'Yes, with position lights', opt_c_en:'No, paragliding is restricted to daytime VMC flights', opt_d_en:'Yes, after 11pm only',
    correct:'C',
    explain_fr:'Le parapente est un aéronef ultraléger soumis aux règles VMC (conditions météo de vol à vue) — vol de jour seulement.',
    explain_en:'Paragliders are ultralight aircraft subject to VMC (visual meteorological conditions) rules — daytime only.',
  },

  // ── TECHNIQUES ────────────────────────────────────────────────────────────
  {
    category:'Techniques', phase:'p1',
    question_fr:'Lors d\'un décollage face (forward launch), quand déclenche-t-on la course?',
    question_en:'During a forward launch, when do you begin your run?',
    opt_a_fr:'Dès que l\'aile commence à monter', opt_b_fr:'Quand l\'aile est au-dessus de la tête, bien équilibrée et les cellules ouvertes',
    opt_c_fr:'Immédiatement en tirant les commandes', opt_d_fr:'Après avoir vérifié le vent seulement',
    opt_a_en:'As soon as the glider starts rising', opt_b_en:'When the glider is overhead, balanced and cells open',
    opt_c_en:'Immediately by pulling the brakes', opt_d_en:'After checking the wind only',
    correct:'B',
    explain_fr:'La course commence uniquement quand l\'aile est bien établie au-dessus de la tête, stable et prête.',
    explain_en:'The run begins only when the glider is well established overhead, stable and ready.',
  },
  {
    category:'Techniques', phase:'p1',
    question_fr:'Le décollage en dos (reverse launch) est privilégié quand:',
    question_en:'The reverse launch is preferred when:',
    opt_a_fr:'Il n\'y a pas de vent', opt_b_fr:'Le vent est entre 5 et 25 km/h',
    opt_c_fr:'Il pleut', opt_d_fr:'L\'aile est neuve',
    opt_a_en:'There is no wind', opt_b_en:'The wind is between 5 and 25 km/h',
    opt_c_en:'It is raining', opt_d_en:'The glider is new',
    correct:'B',
    explain_fr:'Le décollage en dos permet un meilleur contrôle de l\'aile dans des vents modérés, en faisant face à l\'aile.',
    explain_en:'The reverse launch allows better glider control in moderate winds, facing the glider.',
  },
  {
    category:'Techniques', phase:'p1',
    question_fr:'Les "petites oreilles" (big ears) sont utilisées pour:',
    question_en:'"Big ears" are used to:',
    opt_a_fr:'Améliorer la finesse', opt_b_fr:'Augmenter la vitesse de descente et éviter les nuages',
    opt_c_fr:'Réduire la vitesse horizontale', opt_d_fr:'Effectuer des virages plus serrés',
    opt_a_en:'Improve glide ratio', opt_b_en:'Increase descent rate and avoid clouds',
    opt_c_en:'Reduce horizontal speed', opt_d_en:'Make tighter turns',
    correct:'B',
    explain_fr:'Les petites oreilles replient les extrémités de l\'aile pour augmenter la vitesse de descente tout en gardant l\'aile stable.',
    explain_en:'Big ears fold the wingtips to increase descent rate while keeping the glider stable.',
  },
  {
    category:'Techniques', phase:'p1',
    question_fr:'L\'approche en circuit d\'atterrissage standard comprend:',
    question_en:'A standard landing circuit approach includes:',
    opt_a_fr:'Vent arrière, base, finale', opt_b_fr:'Montée, croisière, descente',
    opt_c_fr:'Spirale, arrondi, atterrissage', opt_d_fr:'Face au vent uniquement',
    opt_a_en:'Downwind, base, final', opt_b_en:'Climb, cruise, descent',
    opt_c_en:'Spiral, flare, landing', opt_d_en:'Into wind only',
    correct:'A',
    explain_fr:'Le circuit d\'atterrissage: leg vent arrière (parallel à la piste), base (perpendiculaire), finale (face au vent).',
    explain_en:'Landing circuit: downwind leg (parallel to runway), base (perpendicular), final (into wind).',
  },
  {
    category:'Techniques', phase:'p1',
    question_fr:'L\'arrondi (flare) à l\'atterrissage consiste à:',
    question_en:'The flare at landing consists of:',
    opt_a_fr:'Lever les bras brusquement dès le sol', opt_b_fr:'Appliquer progressivement les deux freins jusqu\'en bas pour freiner la descente',
    opt_c_fr:'Relâcher complètement les freins à 2m du sol', opt_d_fr:'Ne rien faire et laisser l\'aile atterrir naturellement',
    opt_a_en:'Jerking both arms up as you hit the ground', opt_b_en:'Progressively applying both brakes all the way to brake the descent',
    opt_c_en:'Releasing brakes completely at 2m above ground', opt_d_en:'Doing nothing and letting the glider land naturally',
    correct:'B',
    explain_fr:'L\'arrondi progressif permet de convertir la vitesse horizontale en portance et de réduire la vitesse verticale.',
    explain_en:'Progressive flare converts horizontal speed to lift and reduces vertical speed.',
  },
  {
    category:'Techniques', phase:'p2',
    question_fr:'La technique "cobra" au gonflage est utilisée pour:',
    question_en:'The "cobra" inflation technique is used to:',
    opt_a_fr:'Gonfler rapidement dans un vent fort', opt_b_fr:'Gonfler l\'aile progressivement avec les élévateurs avant sans courir',
    opt_c_fr:'Décoller en terrain plat sans vent', opt_d_fr:'Effectuer un décollage acrobatique',
    opt_a_en:'Inflate quickly in strong wind', opt_b_en:'Progressively inflate the glider using front risers without running',
    opt_c_en:'Take off on flat ground with no wind', opt_d_en:'Perform an aerobatic takeoff',
    correct:'B',
    explain_fr:'La technique cobra contrôle le gonflage en tenant les élévateurs A, permettant à l\'aile de monter lentement.',
    explain_en:'The cobra technique controls inflation by holding the A-risers, allowing the glider to rise slowly.',
  },
  {
    category:'Techniques', phase:'p2',
    question_fr:'Le pilotage actif (active flying) consiste à:',
    question_en:'Active flying consists of:',
    opt_a_fr:'Voler avec les freins complètement relâchés', opt_b_fr:'Anticiper et corriger continuellement les mouvements de l\'aile par des inputs frein',
    opt_c_fr:'Effectuer des manœuvres acrobatiques', opt_d_fr:'Utiliser uniquement le déplacement du poids',
    opt_a_en:'Flying with brakes completely released', opt_b_en:'Continuously anticipating and correcting glider movements with brake inputs',
    opt_c_en:'Performing aerobatic maneuvers', opt_d_en:'Using weight shift only',
    correct:'B',
    explain_fr:'Le pilotage actif maintient l\'aile stable en turbulence par des corrections continues et légères des freins.',
    explain_en:'Active flying keeps the glider stable in turbulence through continuous, light brake corrections.',
  },
  {
    category:'Techniques', phase:'p2',
    question_fr:'La spirale engagée est une manœuvre de descente rapide. Le risque principal est:',
    question_en:'An engaged spiral dive is a rapid descent maneuver. The main risk is:',
    opt_a_fr:'Le décrochage de l\'aile', opt_b_fr:'L\'hypoxie par manque d\'oxygène',
    opt_c_fr:'La perte de conscience due aux forces G et la difficulté de sortie', opt_d_fr:'La fermeture frontale',
    opt_a_en:'Glider stall', opt_b_en:'Hypoxia from lack of oxygen',
    opt_c_en:'Loss of consciousness from G-forces and difficulty exiting', opt_d_en:'Frontal collapse',
    correct:'C',
    explain_fr:'Les forces G en spirale peuvent causer une perte de conscience. La sortie requiert une technique précise.',
    explain_en:'G-forces in a spiral can cause loss of consciousness. Exit requires precise technique.',
  },

  // ── SÉCURITÉ ─────────────────────────────────────────────────────────────
  {
    category:'Sécurité', phase:'p1',
    question_fr:'La décision GO / NO-GO avant un vol doit prendre en compte:',
    question_en:'The GO / NO-GO decision before a flight must consider:',
    opt_a_fr:'La météo uniquement', opt_b_fr:'L\'état de l\'équipement uniquement',
    opt_c_fr:'La météo, l\'état de l\'équipement, la condition du pilote, et le site',
    opt_d_fr:'L\'opinion des autres pilotes présents',
    opt_a_en:'Weather only', opt_b_en:'Equipment condition only',
    opt_c_en:'Weather, equipment condition, pilot condition, and site',
    opt_d_en:'Opinion of other pilots present',
    correct:'C',
    explain_fr:'La décision GO/NO-GO est multifactorielle: météo, équipement, fatigue du pilote, expérience, et conditions du site.',
    explain_en:'The GO/NO-GO decision is multifactorial: weather, equipment, pilot fatigue, experience, and site conditions.',
  },
  {
    category:'Sécurité', phase:'p1',
    question_fr:'Si le pilote est dans un nuage (whiteout), il doit:',
    question_en:'If the pilot is inside a cloud (whiteout), they must:',
    opt_a_fr:'Maintenir le cap et attendre de sortir', opt_b_fr:'Faire des grandes oreilles et/ou B-stall pour descendre rapidement',
    opt_c_fr:'Déployer le secours immédiatement', opt_d_fr:'Accélérer avec le speed system',
    opt_a_en:'Maintain heading and wait to exit', opt_b_en:'Deploy big ears and/or B-stall to descend quickly',
    opt_c_en:'Deploy the reserve immediately', opt_d_en:'Accelerate with the speed system',
    correct:'B',
    explain_fr:'Dans un nuage, descendre rapidement avec grandes oreilles ou B-stall pour sortir le plus vite possible.',
    explain_en:'In a cloud, descend quickly with big ears or B-stall to exit as fast as possible.',
  },
  {
    category:'Sécurité', phase:'p1',
    question_fr:'Quelle est la meilleure position du corps lors d\'un atterrissage d\'urgence en terrain difficile?',
    question_en:'What is the best body position during an emergency landing on difficult terrain?',
    opt_a_fr:'Jambes tendues, bras levés', opt_b_fr:'Pieds ensemble, jambes légèrement fléchies, prêt à rouler',
    opt_c_fr:'Position assise dans la sellette jusqu\'au bout', opt_d_fr:'Bras croisés sur la poitrine',
    opt_a_en:'Legs straight, arms up', opt_b_en:'Feet together, knees slightly bent, ready to roll',
    opt_c_en:'Seated position in the harness until the end', opt_d_en:'Arms crossed over chest',
    correct:'B',
    explain_fr:'Position pieds-genoux-hanches-épaule pour amortir l\'impact et éviter les fractures.',
    explain_en:'Feet-knees-hips-shoulder roll position to absorb impact and avoid fractures.',
  },
  {
    category:'Sécurité', phase:'p1',
    question_fr:'Après un incident en vol (fermeture, perte de contrôle), il faut prioritairement:',
    question_en:'After an in-flight incident (collapse, loss of control), you must prioritize:',
    opt_a_fr:'Filmer l\'incident pour analyser plus tard', opt_b_fr:'Gagner de l\'altitude',
    opt_c_fr:'Rétablir le contrôle de l\'aile, maintenir la hauteur, puis décider de la suite',
    opt_d_fr:'Atterrir immédiatement peu importe le terrain',
    opt_a_en:'Film the incident for later analysis', opt_b_en:'Gain altitude',
    opt_c_en:'Restore glider control, maintain altitude, then decide next steps',
    opt_d_en:'Land immediately regardless of terrain',
    correct:'C',
    explain_fr:'L\'ordre des priorités: contrôle de l\'aile → altitude → direction → atterrissage.',
    explain_en:'Priority order: glider control → altitude → direction → landing.',
  },
  {
    category:'Sécurité', phase:'p1',
    question_fr:'Le déploiement du parachute de secours se fait:',
    question_en:'Reserve parachute deployment is done:',
    opt_a_fr:'Uniquement en cas de cravate', opt_b_fr:'Quand l\'aile est incontrôlable et la hauteur suffisante',
    opt_c_fr:'À tout moment si on est stressé', opt_d_fr:'Seulement si l\'aile est décrochée',
    opt_a_en:'Only in case of cravat', opt_b_en:'When the glider is uncontrollable and altitude is sufficient',
    opt_c_en:'At any time when stressed', opt_d_en:'Only if the glider is stalled',
    correct:'B',
    explain_fr:'Le secours se déploie quand l\'aile ne peut pas être récupérée et qu\'il reste assez de hauteur pour son ouverture.',
    explain_en:'The reserve deploys when the glider cannot be recovered and enough altitude remains for it to open.',
  },
  {
    category:'Sécurité', phase:'p2',
    question_fr:'Comment reconnaître une zone de turbulence thermique au sol avant de décoller?',
    question_en:'How to recognize a zone of thermal turbulence on the ground before takeoff?',
    opt_a_fr:'Présence de nuages stratus', opt_b_fr:'Sol uniformément recouvert de gazon',
    opt_c_fr:'Terrains sombres, zones asphaltées, champs cultivés exposés au soleil — indicateurs de déclenchement thermique',
    opt_d_fr:'Présence de rivières ou lacs à proximité',
    opt_a_en:'Presence of stratus clouds', opt_b_en:'Ground uniformly covered with grass',
    opt_c_en:'Dark terrain, asphalt areas, cultivated fields exposed to sun — thermal trigger indicators',
    opt_d_en:'Presence of rivers or lakes nearby',
    correct:'C',
    explain_fr:'Les zones sombres absorbent plus de chaleur et déclenchent des thermiques — à surveiller pour anticiper la turbulence.',
    explain_en:'Dark areas absorb more heat and trigger thermals — watch these to anticipate turbulence.',
  },
  {
    category:'Sécurité', phase:'p2',
    question_fr:'Le signal universel de détresse en parapente (depuis le sol) est:',
    question_en:'The universal distress signal in paragliding (from the ground) is:',
    opt_a_fr:'Agiter les bras au-dessus de la tête', opt_b_fr:'Disposer l\'aile en croix au sol',
    opt_c_fr:'Agiter les bras en X (les deux bras en croix) — signal de détresse aéronautique standard',
    opt_d_fr:'Allumer un feu',
    opt_a_en:'Wave arms above the head', opt_b_en:'Lay the glider in a cross on the ground',
    opt_c_en:'Wave arms in an X (both arms crossed) — standard aeronautical distress signal',
    opt_d_en:'Light a fire',
    correct:'C',
    explain_fr:'Agiter les deux bras en X est le signal de détresse aéronautique reconnu internationalement.',
    explain_en:'Waving both arms in an X is the internationally recognized aeronautical distress signal.',
  },

  // ── PARACHUTE DE SECOURS ──────────────────────────────────────────────────
  {
    category:'Sécurité', phase:'p1',
    question_fr:'Après le déploiement du secours, que faire avec l\'aile principale?',
    question_en:'After reserve deployment, what to do with the main glider?',
    opt_a_fr:'Ne rien faire, l\'aile s\'écrase au sol', opt_b_fr:'La freiner avec les commandes pour éviter qu\'elle ne gonfle et perturbe le secours',
    opt_c_fr:'Retirer les élévateurs', opt_d_fr:'Tirer le parachute encore plus fort',
    opt_a_en:'Do nothing, the glider crashes', opt_b_en:'Brake it with the controls to prevent reinflation that could disturb the reserve',
    opt_c_en:'Remove the risers', opt_d_en:'Pull the reserve harder',
    correct:'B',
    explain_fr:'L\'aile principale peut se regonfler et interférer avec le secours. La freiner évite ce risque.',
    explain_en:'The main glider can reinflate and interfere with the reserve. Braking it prevents this risk.',
  },
  {
    category:'Sécurité', phase:'p1',
    question_fr:'La poignée du secours est généralement:',
    question_en:'The reserve handle is generally:',
    opt_a_fr:'Rouge ou orange, facile à saisir, souvent avec velcro à gauche ou à droite de la sellette',
    opt_b_fr:'Verte pour être visible', opt_c_fr:'Dans le sac à dos', opt_d_fr:'Sur le casque du pilote',
    opt_a_en:'Red or orange, easy to grab, often with velcro on left or right of harness',
    opt_b_en:'Green to be visible', opt_c_en:'In the backpack', opt_d_en:'On the pilot\'s helmet',
    correct:'A',
    explain_fr:'La poignée de secours rouge/orange est fixée sur la sellette, accessible en vol sans avoir à chercher.',
    explain_en:'The red/orange reserve handle is attached to the harness, accessible in flight without searching.',
  },

  // ── QUESTIONS PRATIQUES ───────────────────────────────────────────────────
  {
    category:'Pratique', phase:'p1',
    question_fr:'Combien de décollages face (forward) réussis faut-il pour l\'examen sol P1?',
    question_en:'How many successful forward launches are required for the P1 ground exam?',
    opt_a_fr:'5', opt_b_fr:'10', opt_c_fr:'15', opt_d_fr:'20',
    opt_a_en:'5', opt_b_en:'10', opt_c_en:'15', opt_d_en:'20',
    correct:'B',
    explain_fr:'L\'examen sol P1 requiert 10 gonflages face et 10 gonflages dos réussis.',
    explain_en:'The P1 ground exam requires 10 successful forward and 10 successful reverse inflations.',
  },
  {
    category:'Pratique', phase:'p1',
    question_fr:'Le gonflage sol comprend comme vérification finale:',
    question_en:'Ground inflation includes as a final check:',
    opt_a_fr:'Vérifier que l\'aile est gonflée', opt_b_fr:'Vérifier l\'aile au-dessus (stable, bord d\'attaque ouvert, suspentes claires), le couloir libre, et décider',
    opt_c_fr:'Regarder les autres pilotes', opt_d_fr:'Vérifier uniquement la direction du vent',
    opt_a_en:'Check that the glider is inflated', opt_b_en:'Check the glider above (stable, leading edge open, lines clear), clear corridor, and decide',
    opt_c_en:'Look at other pilots', opt_d_en:'Check wind direction only',
    correct:'B',
    explain_fr:'Avant de courir pour décoller: aile stable et centrée, cellules ouvertes, suspentes non tordues, couloir dégagé.',
    explain_en:'Before running for takeoff: stable centered glider, cells open, lines not twisted, clear corridor.',
  },
  {
    category:'Pratique', phase:'p1',
    question_fr:'Le AUW (All Up Weight) désigne:',
    question_en:'AUW (All Up Weight) refers to:',
    opt_a_fr:'Le poids de l\'aile seule', opt_b_fr:'Le poids total en vol: pilote + sellette + aile + secours + équipement',
    opt_c_fr:'Le poids maximal autorisé par Transports Canada', opt_d_fr:'Le poids nu du pilote uniquement',
    opt_a_en:'Weight of the glider alone', opt_b_en:'Total in-flight weight: pilot + harness + glider + reserve + gear',
    opt_c_en:'Maximum weight authorized by Transport Canada', opt_d_en:'Naked weight of the pilot only',
    correct:'B',
    explain_fr:'AUW = poids pilote + vêtements + casque + eau + sellette + aile + secours + instruments.',
    explain_en:'AUW = pilot weight + clothing + helmet + water + harness + glider + reserve + instruments.',
  },
  {
    category:'Pratique', phase:'p2',
    question_fr:'Pour le décollage en cobra (nose-down), l\'élévateur à saisir est:',
    question_en:'For the cobra (nose-down) launch technique, the riser to use is:',
    opt_a_fr:'L\'élévateur C', opt_b_fr:'L\'élévateur arrière (D)', opt_c_fr:'L\'élévateur A (avant)', opt_d_fr:'Le frein droit uniquement',
    opt_a_en:'The C-riser', opt_b_en:'The rear riser (D)', opt_c_en:'The A-riser (front)', opt_d_en:'Right brake only',
    correct:'C',
    explain_fr:'La technique cobra utilise les élévateurs A pour soulever le bord d\'attaque progressivement.',
    explain_en:'The cobra technique uses the A-risers to lift the leading edge progressively.',
  },
  {
    category:'Pratique', phase:'p2',
    question_fr:'Le B-stall est une technique de descente rapide. Pour l\'activer, le pilote:',
    question_en:'The B-stall is a rapid descent technique. To activate it, the pilot:',
    opt_a_fr:'Tire les deux freins jusqu\'en bas', opt_b_fr:'Tire symétriquement les deux élévateurs B',
    opt_c_fr:'Tire l\'élévateur arrière uniquement', opt_d_fr:'Relâche les freins et met l\'accélérateur',
    opt_a_en:'Pulls both brakes all the way down', opt_b_en:'Symmetrically pulls both B-risers',
    opt_c_en:'Pulls the rear riser only', opt_d_en:'Releases brakes and applies speed bar',
    correct:'B',
    explain_fr:'Le B-stall crée un décrochage partiel en tirant les élévateurs B, augmentant fortement le taux de chute.',
    explain_en:'The B-stall creates a partial stall by pulling the B-risers, greatly increasing the sink rate.',
  },

  // ── MÉTÉO AVANCÉE P2 ──────────────────────────────────────────────────────
  {
    category:'Météorologie', phase:'p2',
    question_fr:'Un inversement thermique se produit quand:',
    question_en:'A thermal inversion occurs when:',
    opt_a_fr:'L\'air se refroidit normalement avec l\'altitude', opt_b_fr:'La température augmente avec l\'altitude, bloquant les thermiques',
    opt_c_fr:'Le vent tourne dans le sens horaire', opt_d_fr:'La pression atmosphérique monte rapidement',
    opt_a_en:'Air cools normally with altitude', opt_b_en:'Temperature increases with altitude, blocking thermals',
    opt_c_en:'Wind turns clockwise', opt_d_en:'Atmospheric pressure rises quickly',
    correct:'B',
    explain_fr:'L\'inversement thermique piège les thermiques sous une couche d\'air chaud, limitant le développement vertical.',
    explain_en:'A thermal inversion traps thermals under a warm air layer, limiting vertical development.',
  },
  {
    category:'Météorologie', phase:'p2',
    question_fr:'Le vent de gradient se réfère à:',
    question_en:'Gradient wind refers to:',
    opt_a_fr:'La différence de vitesse entre le sol et 1000m', opt_b_fr:'Le vent géostrophique modifié par la courbure des isobares',
    opt_c_fr:'Le vent thermique de pente', opt_d_fr:'La vitesse maximale de rafales',
    opt_a_en:'Speed difference between ground and 1000m', opt_b_en:'Geostrophic wind modified by the curvature of isobars',
    opt_c_en:'Slope thermal wind', opt_d_en:'Maximum gust speed',
    correct:'A',
    explain_fr:'En pratique, le vent augmente avec l\'altitude car le frottement au sol ralentit les vents de basse couche.',
    explain_en:'In practice, wind increases with altitude because ground friction slows lower-level winds.',
  },
  {
    category:'Météorologie', phase:'p2',
    question_fr:'Un METAR indique \'TSRA\'. Cela signifie:',
    question_en:'A METAR shows \'TSRA\'. This means:',
    opt_a_fr:'Température supérieure à la normale', opt_b_fr:'Orage avec pluie — vol INTERDIT',
    opt_c_fr:'Vent de travers (crosswind)', opt_d_fr:'Turbulence sévère annoncée',
    opt_a_en:'Temperature above normal', opt_b_en:'Thunderstorm with rain — flight PROHIBITED',
    opt_c_en:'Crosswind', opt_d_en:'Severe turbulence forecast',
    correct:'B',
    explain_fr:'TSRA = Thunderstorm with Rain. Les orages rendent le vol de parapente extrêmement dangereux.',
    explain_en:'TSRA = Thunderstorm with Rain. Thunderstorms make paragliding extremely dangerous.',
  },

  // ── INSTRUMENTS ───────────────────────────────────────────────────────────
  {
    category:'Matériel', phase:'p1',
    question_fr:'Un variomètre mesure:',
    question_en:'A variometer measures:',
    opt_a_fr:'La vitesse horizontale', opt_b_fr:'La vitesse verticale (montée ou descente) en m/s',
    opt_c_fr:'La direction du vent', opt_d_fr:'La charge alaire',
    opt_a_en:'Horizontal speed', opt_b_en:'Vertical speed (climb or descent) in m/s',
    opt_c_en:'Wind direction', opt_d_en:'Wing loading',
    correct:'B',
    explain_fr:'Le variomètre indique la vitesse verticale en m/s — positif = montée (thermique), négatif = descente.',
    explain_en:'The variometer indicates vertical speed in m/s — positive = climbing (thermal), negative = sinking.',
  },
  {
    category:'Matériel', phase:'p2',
    question_fr:'Un altimètre barométrique doit être calé sur:',
    question_en:'A barometric altimeter must be set to:',
    opt_a_fr:'1013 hPa toujours', opt_b_fr:'La pression au niveau de la mer (QNH) ou la pression locale (QFE)',
    opt_c_fr:'La température ambiante', opt_d_fr:'L\'altitude du décollage',
    opt_a_en:'1013 hPa always', opt_b_en:'Sea level pressure (QNH) or local pressure (QFE)',
    opt_c_en:'Ambient temperature', opt_d_en:'Launch altitude',
    correct:'B',
    explain_fr:'L\'altimètre doit être calé sur la pression locale pour donner une altitude exacte.',
    explain_en:'The altimeter must be set to local pressure to give accurate altitude.',
  },
];

export function seedQuizQuestions(db) {
  const count = db.prepare('SELECT COUNT(*) as n FROM quiz_questions').get()?.n || 0;
  if (count > 0) return; // Already seeded
  const stmt = db.prepare(`
    INSERT INTO quiz_questions
      (category, phase, question_fr, question_en,
       opt_a_fr, opt_b_fr, opt_c_fr, opt_d_fr,
       opt_a_en, opt_b_en, opt_c_en, opt_d_en,
       correct, explain_fr, explain_en)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
  `);
  for (const q of QUIZ_QUESTIONS) {
    stmt.run(
      q.category, q.phase, q.question_fr, q.question_en||q.question_fr,
      q.opt_a_fr, q.opt_b_fr, q.opt_c_fr, q.opt_d_fr,
      q.opt_a_en||q.opt_a_fr, q.opt_b_en||q.opt_b_fr,
      q.opt_c_en||q.opt_c_fr, q.opt_d_en||q.opt_d_fr,
      q.correct, q.explain_fr, q.explain_en||q.explain_fr,
    );
  }
}
