// HPAC/ACVL P1-P2 Bilingual Curriculum Seed (EN + FR)
export function seedCurriculum(db) {
  const n = db.prepare('SELECT COUNT(*) as n FROM theory_blocks').get().n;
  if (n > 0) {
    const needsFR = db.prepare('SELECT COUNT(*) as n FROM theory_blocks WHERE title_fr IS NULL').get().n;
    if (needsFR > 0) updateFrenchContent(db);
    return;
  }
  insertAll(db);
}

const p1Theory = [
  { title:'Basic Aerodynamics', title_fr:'Aérodynamique de base', description:'How a paraglider generates lift, drag, stall, and stability fundamentals.', description_fr:"Comment un parapente génère la portance, la traînée, le décrochage et les bases de la stabilité.", content:`Key concepts:\n• How lift is generated (Bernoulli / Newton)\n• Angle of attack and stall angle\n• Pitch, roll and yaw axes\n• Glider stability and pendulum effect\n• Profile design and construction basics\n• Performance: glide ratio, sink rate, trim speed`, content_fr:`Concepts clés :\n• Comment la portance est générée (Bernoulli / Newton)\n• Angle d'attaque et angle de décrochage\n• Axes de tangage, roulis et lacet\n• Stabilité du parapente et effet de pendule\n• Profil de l'aile et construction de base\n• Performance : finesse, taux de chute, vitesse de calage`, phase:'p1', order_idx:1 },
  { title:'Basic Meteorology', title_fr:'Météorologie de base', description:'Wind, temperature, and weather basics relevant to beginner flying.', description_fr:"Vent, température et météo de base pour le vol débutant.", content:`Key concepts:\n• Wind: causes, sea breeze, valley wind, anabatic/katabatic\n• Temperature and its effect on air density\n• Cloud types and what they indicate\n• Reading a basic weather forecast\n• Mechanical and thermic turbulence\n• Venturi effect at launch sites`, content_fr:`Concepts clés :\n• Vent : causes, brise de mer, vent de vallée, anabatique/catabatique\n• Température et son effet sur la densité de l'air\n• Types de nuages et ce qu'ils indiquent\n• Lecture d'une prévision météo de base\n• Turbulences mécaniques et thermiques\n• Effet venturi sur les sites de décollage`, phase:'p1', order_idx:2 },
  { title:'Techniques of Flight', title_fr:'Techniques de vol', description:'Fundamental flying techniques for P1 level.', description_fr:"Techniques de vol fondamentales pour le niveau P1.", content:`Key concepts:\n• Axes of movement: pitch, roll, yaw\n• Forward and reverse inflation technique\n• Launch and abort procedures\n• Airspeed vs ground speed vs wind speed\n• Brake input and turn coordination\n• Final approach and landing technique\n• Post-landing canopy control`, content_fr:`Concepts clés :\n• Axes de mouvement : tangage, roulis, lacet\n• Technique de gonflage face voile et dos voile\n• Procédures de décollage et d'abandon\n• Vitesse air vs vitesse sol vs vitesse du vent\n• Utilisation des freins et coordination des virages\n• Technique d'approche finale et d'atterrissage\n• Contrôle de l'aile après l'atterrissage`, phase:'p1', order_idx:3 },
  { title:'Awareness of Air Regulations', title_fr:'Connaissance de la règlementation aérienne', description:'Canadian airspace rules and HPAC/ACVL regulatory framework.', description_fr:"Règles de l'espace aérien canadien et cadre réglementaire ACVL/HPAC.", content:`Key concepts:\n• Transport Canada and HPAC/ACVL roles\n• HPAC rating system overview (P1-P5)\n• VFR rules and cloud clearance requirements\n• Airspace classifications (TP6010)\n• Rules of the ridge (right of way)\n• Radio use requirements and protocols\n• HPAC standard waiver and assumption of risk`, content_fr:`Concepts clés :\n• Rôles de Transports Canada et ACVL/HPAC\n• Aperçu du système de qualifications ACVL (P1-P5)\n• Règles VFR et distances réglementaires par rapport aux nuages\n• Classifications de l'espace aérien (TP6010)\n• Priorités le long d'un relief\n• Exigences et protocoles d'utilisation du radio\n• Renonciation et acceptation des risques ACVL/HPAC`, phase:'p1', order_idx:4 },
  { title:'Human Factors & Safety', title_fr:'Facteurs humains et sécurité', description:'Pilot-in-command concept, decision making, and risk awareness.', description_fr:"Concept du commandant de bord, prise de décision et conscience du risque.", content:`Key concepts:\n• Concept of pilot-in-command and transfer of responsibility\n• Physical fitness and flying readiness\n• Peer pressure and go/no-go decision making\n• Stress and its effect on performance\n• Ego as a risk factor\n• Positive pilot attitude`, content_fr:`Concepts clés :\n• Concept du commandant de bord et transfert de responsabilité\n• Condition physique et état de préparation au vol\n• Pression des pairs et prise de décision vol/no-vol\n• Stress et son effet sur la performance\n• Ego comme facteur de risque\n• Attitude positive du pilote`, phase:'p1', order_idx:5 },
  { title:'Environment & Site Assessment', title_fr:"Environnement et évaluation du site", description:'Reading your flying site and conditions before and during flight.', description_fr:"Lire son site de vol et les conditions avant et pendant le vol.", content:`Key concepts:\n• Conditions observation at launch\n• Wind direction and velocity assessment\n• Terrain shape and its effect on airflow\n• Obstacle identification at launch and LZ\n• Identifying safe abort zones\n• LZ protocol and traffic awareness`, content_fr:`Concepts clés :\n• Observation des conditions au décollage\n• Évaluation de la direction et de la vitesse du vent\n• Forme du terrain et son effet sur l'aérologie\n• Identification des obstacles au décollage et à l'atterrissage\n• Identification des zones d'abandon sécuritaires\n• Protocole de terrain d'atterrissage et gestion du trafic`, phase:'p1', order_idx:6 },
  { title:'Equipment & Pre-flight', title_fr:'Équipement et pré-vol', description:'Paraglider, harness, and reserve inspection and care.', description_fr:"Inspection et entretien du parapente, de la sellette et du secours.", content:`Key concepts:\n• Glider layout and line check\n• Harness adjustment and connection check\n• Reserve parachute basics (location, handle)\n• Pre-flight inspection checklist\n• Equipment maintenance fundamentals\n• Radio use and communication protocols\n• Proper packing, storage, and care`, content_fr:`Concepts clés :\n• Disposition de l'aile et vérification des suspentes\n• Réglage de la sellette et vérification de la connexion\n• Bases du parachute de secours (emplacement, poignée)\n• Liste de contrôle pré-vol\n• Fondamentaux de l'entretien de l'équipement\n• Utilisation du radio et protocoles de communication\n• Pliage, entreposage et soins appropriés`, phase:'p1', order_idx:7 },
  { title:'Emergency Procedures', title_fr:"Procédures d'urgence", description:'Recognition and response to in-flight incidents.', description_fr:"Reconnaissance et réponse aux incidents en vol.", content:`Key concepts:\n• Stall recognition and exit\n• Spin recognition and exit\n• Asymmetric collapse recognition and exit\n• Frontal collapse recognition and exit\n• Deep stall / parachutal stall recognition and exit\n• Spiral dive recognition and exit\n• Reserve deployment: when and how\n• Parachute landing fall (PLF)\n• Tree landing technique\n• Water landing procedure\n• Power line avoidance`, content_fr:`Concepts clés :\n• Reconnaissance et sortie de décrochage\n• Reconnaissance et sortie de vrille\n• Reconnaissance et sortie d'une fermeture asymétrique\n• Reconnaissance et sortie d'une fermeture frontale\n• Reconnaissance et sortie d'une phase parachutale\n• Reconnaissance et sortie de piqué en spirale\n• Déploiement du secours : quand et comment\n• Posé roulé-boulé (PRB)\n• Technique d'atterrissage en branchage\n• Procédure d'amerrissage\n• Évitement des lignes électriques`, phase:'p1', order_idx:8 },
  { title:"Incident & Accident Reporting", title_fr:"Rapport d'incident et d'accident", description:'HPAC reporting requirements and responsibilities.', description_fr:"Exigences et responsabilités en matière de rapports ACVL.", content:`Key concepts:\n• Definitions: incident vs accident\n• HPAC online reporting system\n• What must be reported and when\n• Pilot responsibilities after an incident\n• Insurance and liability implications\n• Learning from accidents in the community`, content_fr:`Concepts clés :\n• Définitions : incident vs accident\n• Système de rapports en ligne de l'ACVL\n• Ce qui doit être rapporté et quand\n• Responsabilités du pilote après un incident\n• Implications pour l'assurance et la responsabilité\n• Apprendre des accidents dans la communauté`, phase:'p1', order_idx:9 },
];

const p2Theory = [
  { title:'Advanced Aerodynamics', title_fr:'Aérodynamique avancée', description:'In-depth glider aerodynamics for P2 level.', description_fr:"Aérodynamique approfondie du parapente pour le niveau P2.", content:`Key concepts:\n• Airflow over profile, lift and drag polars\n• Profile design and glider construction details\n• Stall: accelerated stall, asymmetric stall\n• Glider stability: pitch, roll, yaw in detail\n• Wind loading and weight effects\n• Performance: speed-to-fly theory`, content_fr:`Concepts clés :\n• Écoulement de l'air sur le profil, polaires de portance et traînée\n• Profil de l'aile et construction du parapente en détail\n• Décrochage : décrochage accéléré, décrochage asymétrique\n• Stabilité du parapente : tangage, roulis, lacet en détail\n• Charge alaire et effets du poids\n• Performance : théorie de la vitesse de finesse`, phase:'p2', order_idx:1 },
  { title:'Advanced Meteorology', title_fr:'Météorologie avancée', description:'Weather systems, thermals, and site-specific conditions for P2.', description_fr:"Systèmes météo, thermiques et conditions spécifiques au site pour P2.", content:`Key concepts:\n• Thermal generation, structure, and triggering\n• Thermic turbulence: types and recognition\n• Wake turbulence and mechanical turbulence\n• Air masses and frontal systems\n• Humidity, density, and pressure effects\n• High-altitude conditions: hypoxia, cloud suck, anabatic/katabatic`, content_fr:`Concepts clés :\n• Génération, structure et déclenchement des thermiques\n• Turbulences thermiques : types et reconnaissance\n• Turbulences de sillage et mécaniques\n• Masses d'air et systèmes frontaux\n• Effets de l'humidité, de la densité et de la pression\n• Conditions de haute altitude : hypoxie, aspiration nuageuse, anabatique/catabatique`, phase:'p2', order_idx:2 },
  { title:'Advanced Techniques of Flight', title_fr:'Techniques de vol avancées', description:'P2-level flying skills and manoeuvre theory.', description_fr:"Habiletés de vol et théorie des manoeuvres de niveau P2.", content:`Key concepts:\n• PTU, PTS, PT8 landing approaches\n• Accurate spot landing planning\n• Controlled turns at various bank angles\n• Big-ear technique: entry, descent, exit\n• Speed bar / accelerator system use\n• One-handed flying and weight-shift turns\n• Rear-riser turns\n• Ridge rules and traffic management\n• Rapid descent techniques`, content_fr:`Concepts clés :\n• Prises de terrain PTU, PTS, PT8\n• Planification d'atterrissage de précision\n• Virages contrôlés à différentes inclinaisons\n• Technique des grandes oreilles : entrée, descente, sortie\n• Utilisation de l'accélérateur\n• Pilotage à une main et virages en appui-sellette\n• Virages aux élévateurs arrières\n• Règles de priorité et gestion du trafic\n• Techniques de descente rapide`, phase:'p2', order_idx:3 },
  { title:'Advanced Air Regulations', title_fr:'Règlementation aérienne avancée', description:'Detailed airspace rules and right-of-way for P2 pilots.', description_fr:"Règles de l'espace aérien et priorités détaillées pour les pilotes P2.", content:`Key concepts:\n• Transport Canada airspace in detail (TP6010)\n• Cloud flying rules and restrictions\n• VFR flight rules in detail\n• Airspace classifications and NOTAMs\n• Ridge rules and right-of-way in detail\n• Radio: frequencies, protocols, mandatory use\n• HPAC endorsement requirements`, content_fr:`Concepts clés :\n• Espace aérien de Transports Canada en détail (TP6010)\n• Règles et restrictions de vol à proximité des nuages\n• Règles de vol VFR en détail\n• Classifications de l'espace aérien et NOTAMs\n• Priorités le long d'un relief en détail\n• Radio : fréquences, protocoles, utilisation obligatoire\n• Exigences d'annotations ACVL`, phase:'p2', order_idx:4 },
  { title:'Advanced Human Factors', title_fr:'Facteurs humains avancés', description:'Physical and psychological factors at P2 level.', description_fr:"Facteurs physiques et psychologiques au niveau P2.", content:`Key concepts:\n• Physical factors: hypoxia, hypothermia, vertigo, dehydration\n• Psychological: alcohol, medication, drugs, fatigue\n• Peer pressure and get-there-itis\n• Stress, ego, and risk homeostasis\n• Decision-making models for pilots`, content_fr:`Concepts clés :\n• Facteurs physiques : hypoxie, hypothermie, vertige, déshydratation\n• Facteurs psychologiques : alcool, médicaments, drogues, fatigue\n• Pression des pairs et biais d'engagement\n• Stress, ego et homéostasie du risque\n• Modèles de prise de décision pour les pilotes`, phase:'p2', order_idx:5 },
  { title:'Equipment — Maintenance & Selection', title_fr:'Équipement — Entretien et choix du matériel', description:'Gear selection, maintenance, and reserve parachute at P2 level.', description_fr:"Choix du matériel, entretien et parachute de secours au niveau P2.", content:`Key concepts:\n• Choosing a glider appropriate for P2 skill level\n• Understanding certification classes (EN-A, EN-B, etc.)\n• Harness selection and back protection\n• Reserve parachute: types, deployment, repacking\n• Inspection cycles and when to seek service`, content_fr:`Concepts clés :\n• Choisir un parapente adapté au niveau P2\n• Comprendre les classes de certification (EN-A, EN-B, etc.)\n• Choix de la sellette et protection dorsale\n• Parachute de secours : types, déploiement, repliage\n• Cycles d'inspection et quand faire réviser`, phase:'p2', order_idx:6 },
  { title:'Advanced Emergency Procedures', title_fr:"Procédures d'urgence avancées", description:'P2-level incident management and rapid descent techniques.', description_fr:"Gestion des incidents et techniques de descente rapide au niveau P2.", content:`Key concepts:\n• Rapid descent techniques: big ears, spiral, B-line stall\n• Asymmetric collapse: full (50% span) recovery\n• Frontal collapse: recognition, recovery\n• Induced spin: avoidance and recovery\n• Reserve deployment in simulated harness environment\n• Water, tree, power line landing procedures\n• Strong wind landing and anti-drag techniques`, content_fr:`Concepts clés :\n• Techniques de descente rapide : grandes oreilles, spirale, décrochage B\n• Fermeture asymétrique : récupération complète (50% de l'envergure)\n• Fermeture frontale : reconnaissance et récupération\n• Vrille provoquée : évitement et récupération\n• Déploiement du secours en simulation dans la sellette\n• Procédures d'atterrissage en eau, branchage, lignes électriques\n• Procédures d'atterrissage par vent fort et techniques anti-traîne`, phase:'p2', order_idx:7 },
];

const ghPF = [
  {title:'#1 — Conditions observation',title_fr:'#1 — Observation des conditions',description:'Assess wind, weather, and site conditions before approaching launch.',description_fr:"Évaluer le vent, la météo et les conditions du site avant d'approcher le décollage.",order_idx:1},
  {title:'#2 — Positive pilot attitude',title_fr:'#2 — Attitude positive du pilote',description:'Self-assessment of physical and mental fitness to fly today.',description_fr:"Auto-évaluation de la condition physique et mentale pour voler aujourd'hui.",order_idx:2},
  {title:'#3 — Wing preparation, layout and inspection',title_fr:"#3 — Préparation, disposition et inspection de l'aile",description:'Proper canopy layout, line check, and pre-flight inspection of the glider.',description_fr:"Disposition correcte de l'aile, vérification des suspentes et inspection pré-vol du parapente.",order_idx:3},
  {title:'#4 — Obstacles at launch and landing',title_fr:"#4 — Obstacles au décollage et à l'atterrissage",description:'Identify and brief all obstacles at launch site and LZ.',description_fr:"Identifier et noter tous les obstacles au site de décollage et dans la zone d'atterrissage.",order_idx:4},
  {title:'#5 — Harness adjustment',title_fr:'#5 — Ajustement de la sellette',description:'Correct harness fitting, leg loop and chest strap adjustment, and connection check.',description_fr:'Ajustement correct de la sellette, réglage des jambières et sangle de poitrine, vérification de connexion.',order_idx:5},
  {title:'#6 — Airspeed / ground speed / wind speed',title_fr:'#6 — Vitesse air / vitesse sol / vitesse vent',description:'Understand the relationship between air, ground, and wind speed in flight planning.',description_fr:"Comprendre la relation entre vitesse air, vitesse sol et vitesse du vent dans la planification du vol.",order_idx:6},
  {title:'#7 — Equipment maintenance',title_fr:"#7 — Entretien de l'équipement",description:'Basic care, inspection, and maintenance of glider, harness, and accessories.',description_fr:'Soins de base, inspection et entretien du parapente, de la sellette et des accessoires.',order_idx:7},
  {title:'#8 — Radio protocols',title_fr:"#8 — Protocoles d'utilisation des radios",description:'Correct radio use: frequencies, call format, communication during flight.',description_fr:"Utilisation correcte du radio : fréquences, format d'appel, communication en vol.",order_idx:8},
  {title:'#9 — Pre-flight inspection',title_fr:'#9 — Inspection pré-vol',description:'Full pre-flight inspection of all equipment before every flight.',description_fr:"Inspection pré-vol complète de tout l'équipement avant chaque vol.",order_idx:9},
  {title:'#10 — Pre-flight checklist',title_fr:'#10 — Liste de contrôle pré-vol',description:'Use of a structured checklist immediately before inflation and launch.',description_fr:"Utilisation d'une liste de contrôle structurée immédiatement avant le gonflage et le décollage.",order_idx:10},
];
const ghL = [
  {title:'#11 — Aligning wind, pilot, and wing',title_fr:'#11 — Centrage aile – pilote – vent',description:'Correctly position pilot and wing relative to wind direction before inflation.',description_fr:"Positionner correctement le pilote et l'aile par rapport à la direction du vent avant le gonflage.",order_idx:11},
  {title:'#12 — Inflation timing and impetus',title_fr:'#12 — Choix du moment du gonflage, impulsion',description:'Apply the correct timing and energy to the initial inflation pull.',description_fr:'Appliquer le bon moment et l\'énergie correcte à la traction initiale de gonflage.',order_idx:12},
  {title:'#13 — Paraglider inflation speed control',title_fr:'#13 — Vitesse de gonflage du parapente',description:'Control the rate of canopy rise during inflation to avoid overshoot.',description_fr:"Contrôler la vitesse de montée de l'aile pendant le gonflage pour éviter le dépassement.",order_idx:13},
  {title:'#14 — Visual control during inflation',title_fr:'#14 — Contrôle visuel',description:'Check canopy overhead visually before committing to launch.',description_fr:"Vérifier visuellement l'aile au-dessus avant de s'engager dans le décollage.",order_idx:14},
  {title:'#15 — Ground handling — roll control',title_fr:'#15 — Contrôle au sol – contrôle du roulis',description:'Maintain lateral control of the canopy during kiting on the ground.',description_fr:"Maintenir le contrôle latéral de l'aile pendant le kite au sol.",order_idx:15},
  {title:'#16 — Control in strong wind (up to 20 km/h)',title_fr:'#16 — Contrôle statique vent fort (20 km/h max)',description:'Kite and control the canopy confidently in winds up to 20 km/h.',description_fr:"Kiter et contrôler l'aile en confiance dans des vents jusqu'à 20 km/h.",order_idx:16},
  {title:'#17 — Launch in light or no wind (up to 8 km/h)',title_fr:'#17 — Décollage vent faible ou nul (8 km/h max)',description:'Controlled forward inflation launch in light or calm conditions.',description_fr:'Décollage face voile contrôlé en conditions de vent faible ou nul.',order_idx:17},
  {title:'#18 — Launch in steady wind (up to 20 km/h)',title_fr:'#18 — Décollage vent soutenu (20 km/h max)',description:'Controlled reverse inflation launch in steady winds up to 20 km/h.',description_fr:"Décollage dos voile contrôlé dans un vent soutenu jusqu'à 20 km/h.",order_idx:18},
];
const ghPS = [
  {title:'Pre-Solo — Stall recognition and exit (simulator)',title_fr:'Pré-solo — Reconnaissance et sortie de décrochage (simulateur)',description:'Recognise the signs of an impending stall and execute correct exit.',description_fr:"Reconnaître les signes d'un décrochage imminent et exécuter la sortie correcte.",order_idx:19},
  {title:'Pre-Solo — Spin recognition and exit (simulator)',title_fr:'Pré-solo — Reconnaissance et sortie de vrille (simulateur)',description:'Recognise and recover from a spin in a simulated environment.',description_fr:'Reconnaître et se rétablir d\'une vrille en environnement simulé.',order_idx:20},
  {title:'Pre-Solo — Spiral dive recognition and exit (simulator)',title_fr:'Pré-solo — Reconnaissance et sortie de piqué en spirale (simulateur)',description:'Recognise and recover from a spiral dive.',description_fr:"Reconnaître et se rétablir d'un piqué en spirale.",order_idx:21},
  {title:'Pre-Solo — Collapse recognition and exit (simulator)',title_fr:"Pré-solo — Reconnaissance et sortie d'une fermeture (simulateur)",description:'Recognise asymmetric and frontal collapse and execute correct recovery.',description_fr:"Reconnaître une fermeture asymétrique et frontale et exécuter le rétablissement correct.",order_idx:22},
  {title:'Pre-Solo — Deep stall recognition and exit (simulator)',title_fr:"Pré-solo — Reconnaissance et sortie d'une phase parachutale (simulateur)",description:'Recognise and recover from a deep stall / parachutal stall.',description_fr:"Reconnaître et se rétablir d'une phase parachutale.",order_idx:23},
  {title:'Pre-Solo — Inflation exercises',title_fr:'Pré-solo — Exercices de gonflage',description:'Multiple repeated forward and reverse inflation practice sessions.',description_fr:'Séances répétées de pratique de gonflage face voile et dos voile.',order_idx:24},
  {title:'Pre-Solo — Dual command (tandem) training',title_fr:'Pré-solo — Formation en double commande',description:'Tandem flight with instructor under dual command.',description_fr:"Vol en tandem avec l'instructeur sous double commande.",order_idx:25},
  {title:'Pre-Solo — Crosswind technique',title_fr:'Pré-solo — Vent traversier',description:'Launch and ground handling in crosswind conditions.',description_fr:'Décollage et maniement au sol en conditions de vent traversier.',order_idx:26},
  {title:'Pre-Solo — Communication failure procedure',title_fr:'Pré-solo — Panne de communication',description:'Understand and practise procedures if radio contact is lost during flight.',description_fr:'Comprendre et pratiquer les procédures en cas de perte de contact radio en vol.',order_idx:27},
  {title:'Pre-Solo — Emergency procedures briefing',title_fr:"Pré-solo — Procédures d'urgence",description:'Full briefing and demonstration of all emergency procedures.',description_fr:"Briefing complet et démonstration de toutes les procédures d'urgence.",order_idx:28},
  {title:'Pre-Solo — Reserve parachute usage (harness simulation)',title_fr:'Pré-solo — Utilisation du parachute de secours (simulation)',description:'Practice reserve deployment handle location and throw in a simulated harness.',description_fr:"Pratiquer la localisation et le lancer de la poignée du secours dans une sellette simulée.",order_idx:29},
];
const airIF = [
  {title:'#19 — Familiarisation tandem flight',title_fr:'#19 — Tandem pédagogique',description:'First flight experience under dual command with instructor.',description_fr:"Première expérience de vol sous double commande avec l'instructeur.",order_idx:1},
  {title:'#20 — Corrections and small turns',title_fr:'#20 — Corrections et petits virages',description:'Make small brake corrections to maintain heading and perform gentle turns.',description_fr:'Faire de petites corrections de freins pour maintenir le cap et effectuer des virages doux.',order_idx:2},
  {title:'#21 — Response to radio inputs',title_fr:'#21 — Réaction aux consignes radio',description:'Follow instructor radio instructions during flight promptly and correctly.',description_fr:"Suivre rapidement et correctement les instructions radio de l'instructeur en vol.",order_idx:3},
  {title:'#22 — Final approach in straight line',title_fr:'#22 — Finale en ligne droite, position debout',description:'Fly a straight final approach to a pre-selected target, out of harness position.',description_fr:'Voler une finale droite vers une cible prédéterminée, en position debout.',order_idx:4},
  {title:'#23 — Observation of flight conditions',title_fr:'#23 — Observation des conditions de vol',description:'Monitor and interpret changing conditions during flight.',description_fr:'Surveiller et interpréter les conditions changeantes pendant le vol.',order_idx:5},
  {title:'#24 — Planning and respecting the flight plan',title_fr:'#24 — Planification et respect du plan de vol',description:'Stick to a pre-briefed flight plan including flight path and areas to avoid.',description_fr:"Respecter un plan de vol pré-briefé incluant la trajectoire et les zones à éviter.",order_idx:6},
  {title:'#25 — Heading control and drift correction',title_fr:'#25 — Maintien du cap – contrôle de la dérive',description:'Maintain a heading and make correct inputs to counteract crosswind drift.',description_fr:'Maintenir un cap et effectuer les corrections appropriées pour contrer la dérive.',order_idx:7},
  {title:'#26 — 90°, 180°, and 360° turns',title_fr:'#26 — Virages 90°, 180°, 360°',description:'Execute accurate turns of 90, 180, and 360 degrees with controlled bank angle.',description_fr:'Exécuter des virages précis de 90, 180 et 360 degrés avec inclinaison contrôlée.',order_idx:8},
  {title:"#27 — Weight-shift turns",title_fr:"#27 — Virage à l'appui sellette",description:'Initiate and sustain turns using weight shift with minimal brake input.',description_fr:'Initier et maintenir des virages en appui sellette avec un minimum de freins.',order_idx:9},
  {title:'#28 — Getting into sitting position',title_fr:'#28 — Passage assis dans la sellette',description:'Transition smoothly into seated harness position after launch.',description_fr:'Passer en douceur en position assise dans la sellette après le décollage.',order_idx:10},
  {title:'#29 — Control of pitch and roll',title_fr:'#29 — Démonstration du contrôle du tangage et du roulis',description:'Demonstrate deliberate pitch and roll control inputs and their effects.',description_fr:'Démontrer des entrées délibérées de contrôle du tangage et du roulis et leurs effets.',order_idx:11},
  {title:'#30 — Speed to fly (minimum sink / best glide)',title_fr:'#30 — Compréhension des vitesses de vol (taux de chute mini, finesse max)',description:'Identify and fly at minimum sink speed and best glide speed.',description_fr:'Identifier et voler à la vitesse de taux de chute minimum et de finesse maximum.',order_idx:12},
  {title:'#31 — Turns at various bank angles',title_fr:'#31 — Virages à différentes inclinaisons',description:'Perform turns from shallow to steep bank angles with consistent control.',description_fr:'Effectuer des virages de faible à forte inclinaison avec un contrôle constant.',order_idx:13},
  {title:'#32 — Small ears (symmetrical and asymmetrical)',title_fr:'#32 — Petites oreilles symétriques et asymétriques',description:'Apply and release small ear tips for increased descent rate.',description_fr:'Appliquer et relâcher les petites oreilles pour augmenter le taux de chute.',order_idx:14},
  {title:'#33 — Piloting with ears + speedbar',title_fr:'#33 — Pilotage aux oreilles + accélérateur',description:'Combine small ears with speedbar for maximum controlled descent.',description_fr:"Combiner les petites oreilles avec l'accélérateur pour une descente contrôlée maximale.",order_idx:15},
  {title:"#34 — Use of accelerator (speedbar)",title_fr:"#34 — Utilisation de l'accélérateur",description:'Apply and release the speedbar smoothly while maintaining control.',description_fr:"Appliquer et relâcher l'accélérateur en douceur tout en maintenant le contrôle.",order_idx:16},
  {title:'#35 — Landing in steady wind (up to 20 km/h)',title_fr:'#35 — Atterrissage vent soutenu (20 km/h max)',description:'Execute a planned, controlled landing in winds up to 20 km/h.',description_fr:"Exécuter un atterrissage planifié et contrôlé dans des vents jusqu'à 20 km/h.",order_idx:17},
  {title:'#36 — Manage and exit high-bank 360° turns',title_fr:'#36 — Gestion et sortie de virage 360° engagé (spirale)',description:'Enter, sustain, and exit high-bank 360° turns safely.',description_fr:"Entrer, maintenir et sortir de virages 360° à forte inclinaison en sécurité.",order_idx:18},
  {title:'#37 — One-handed flying',title_fr:'#37 — Pilotage à une main',description:'Demonstrate controlled flight using only one brake while maintaining heading.',description_fr:'Démontrer un vol contrôlé avec un seul frein tout en maintenant le cap.',order_idx:19},
];
const airL = [
  {title:'#38 — Parachute landing fall (PLF)',title_fr:'#38 — Posé roulé-boulé (PRB)',description:'Demonstrate correct PLF technique for hard or off-target landings.',description_fr:'Démontrer la technique correcte de posé roulé-boulé pour les atterrissages durs ou décentrés.',order_idx:20},
  {title:'#39 — Tree landing technique',title_fr:'#39 — Techniques de branchage',description:'Know and explain the correct technique for landing in trees.',description_fr:"Connaître et expliquer la technique correcte pour atterrir dans les arbres.",order_idx:21},
  {title:'#40 — Folding the wing',title_fr:'#40 — Pliage de la voile',description:'Pack and fold the canopy correctly after landing in field conditions.',description_fr:"Plier et ranger l'aile correctement après l'atterrissage sur le terrain.",order_idx:22},
  {title:'#41 — Spot landing',title_fr:'#41 — Atterrissage de précision',description:'Land accurately on a pre-selected spot within an acceptable radius.',description_fr:"Atterrir précisément sur un point prédéterminé dans un rayon acceptable.",order_idx:23},
  {title:'#42 — Paragliding rosette (champignon)',title_fr:'#42 — Mise en champignon du parapente',description:'Perform a rosette (figure-eight or S-turn) landing approach accurately.',description_fr:"Effectuer une mise en champignon lors de l'approche d'atterrissage.",order_idx:24},
];
const airP2 = [
  {title:'P2 — Consistent landing approaches: PTU, PTS, PT8, accurate spot',title_fr:'P2 — Approches constantes : PTU, PTS, PT8, atterrissage précis',description:'Consistent ability to perform PTU, S-turn, figure-eight, and accurate planned landings.',description_fr:"Capacité constante d'effectuer des PTU, PTS, PT8 et des atterrissages précis planifiés.",order_idx:25},
  {title:'P2 — Reserve parachute preflight',title_fr:'P2 — Pré-vol avec parachute de secours',description:'Layout and preflight of canopy, harness, and backup reserve parachute.',description_fr:"Disposition correcte de l'aile et pré-vol de l'aile, de la sellette et du parachute de secours.",order_idx:26},
  {title:'P2 — Site analysis and flight plan',title_fr:'P2 — Analyse du site et plan de vol',description:'Reliable analysis of site conditions and self, including flight path and obstacles.',description_fr:"Analyse fiable des conditions générales du site et de soi, avec trajectoire de vol et obstacles.",order_idx:27},
  {title:'P2 — Consecutive forward and reverse inflations',title_fr:'P2 — Gonflages face voile et dos voile consécutifs',description:'Consistent forward and reverse inflations with visual check and surge dampening each time.',description_fr:"Gonflages face voile et dos voile constants avec temporisation et vérification visuelle de l'aile à chaque fois.",order_idx:28},
  {title:'P2 — Controlled kiting',title_fr:'P2 — Contrôle du parapente au sol (kite)',description:'Demonstrate sustained, controlled kiting of the canopy in varying conditions.',description_fr:"Démontrer un kite soutenu et contrôlé de l'aile dans des conditions variées.",order_idx:29},
  {title:'P2 — Consistent reliable pre-flight checks',title_fr:'P2 — Vérifications pré-vol constantes et fiables',description:'Consistent, complete pre-flight check before every flight without prompting.',description_fr:'Vérification pré-vol constante et complète avant chaque vol sans rappel.',order_idx:30},
  {title:'P2 — Launching in various wind conditions',title_fr:'P2 — Décollages dans des conditions de vent variées',description:'Reliable launching in light, moderate, and strong wind conditions.',description_fr:'Décollages fiables en conditions de vent léger, modéré et fort.',order_idx:31},
  {title:"P2 — Brief and instruct ground crew",title_fr:"P2 — Expliquer les techniques d'aide au décollage à l'équipe au sol",description:'Brief a ground crew on assisted launch techniques and when required.',description_fr:"Expliquer à une équipe au sol les techniques d'aide au décollage et quand elles sont nécessaires.",order_idx:32},
  {title:'P2 — Big-ear technique',title_fr:'P2 — Technique de descente rapide aux oreilles',description:'Demonstrate big-ear entry, stable descent, and clean exit.',description_fr:"Démontrer l'entrée aux grandes oreilles, la descente stable et la sortie propre.",order_idx:33},
  {title:'P2 — Rear-riser turns',title_fr:'P2 — Virages aux élévateurs arrières',description:'Demonstrate controlled turns using rear risers.',description_fr:'Démontrer des virages contrôlés en utilisant les élévateurs arrières.',order_idx:34},
  {title:'P2 — Strong wind landing and anti-drag',title_fr:'P2 — Atterrissage par vent fort et anti-traîne',description:'Demonstrate or explain strong wind landing procedures and canopy disabling techniques.',description_fr:"Démontrer ou expliquer les procédures d'atterrissage par vent fort et les techniques d'élimination de la traction de l'aile.",order_idx:35},
  {title:'P2 — Lengthen and shorten flight path',title_fr:'P2 — Allonger ou raccourcir la trajectoire de vol',description:'Demonstrate how to extend or cut short the flight path.',description_fr:'Démontrer comment allonger ou raccourcir la trajectoire de vol par PTS et approche directe.',order_idx:36},
  {title:'P2 — Right-of-way traffic rules in flight',title_fr:'P2 — Règles de priorité en vol',description:'Demonstrate correct right-of-way rules including ridge protocol.',description_fr:"Démontrer les règles de priorité correctes incluant le protocole de pente.",order_idx:37},
  {title:'P2 — Speedbar / accelerating system',title_fr:"P2 — Usage approprié du système d'accélérateur",description:'Demonstrate proper use of the speedbar while maintaining control and heading.',description_fr:"Démontrer l'usage approprié de l'accélérateur tout en maintenant le contrôle et le cap.",order_idx:38},
  {title:'P2 — Reserve deployment (harness simulation)',title_fr:'P2 — Déploiement du secours (simulation dans la sellette)',description:'Reserve deployment while hanging in a harness in a simulated environment.',description_fr:'Déploiement du secours accroché dans la sellette en environnement simulé.',order_idx:39},
];
const examDefs = [
  {title:'P1 Theory Exam',title_fr:'Examen théorique P1',description:'HPAC/ACVL written exam. Required for P1 Beginner rating.',description_fr:'Examen écrit ACVL/HPAC. Requis pour la qualification P1 Débutant.',type:'theory',phase:'p1',order_idx:1},
  {title:'P2 Theory Exam',title_fr:'Examen théorique P2',description:'HPAC/ACVL written exam. Required for P2 Novice rating.',description_fr:'Examen écrit ACVL/HPAC. Requis pour la qualification P2 Novice.',type:'theory',phase:'p2',order_idx:2},
  {title:'Forward Launch — Practical Exam',title_fr:'Décollage face voile — Examen pratique',description:'Practical exam: consistent, controlled forward inflation and launch. Assessed by instructor.',description_fr:'Examen pratique : gonflage face voile constant et contrôlé suivi d\'un décollage. Évalué par l\'instructeur.',type:'practical',phase:'p1',order_idx:3},
  {title:'Reverse Launch — Practical Exam',title_fr:'Décollage dos voile — Examen pratique',description:'Practical exam: consistent, controlled reverse inflation and launch. Assessed by instructor.',description_fr:"Examen pratique : gonflage dos voile constant et contrôlé suivi d'un décollage. Évalué par l'instructeur.",type:'practical',phase:'p1',order_idx:4},
];

function insertAll(db) {
  const iB = db.prepare(`INSERT INTO theory_blocks (title,title_fr,description,description_fr,content,content_fr,phase,order_idx) VALUES (@title,@title_fr,@description,@description_fr,@content,@content_fr,@phase,@order_idx)`);
  const iE = db.prepare(`INSERT INTO exercises (title,title_fr,description,description_fr,category,order_idx,requires_signoff) VALUES (@title,@title_fr,@description,@description_fr,@category,@order_idx,1)`);
  const iX = db.prepare(`INSERT INTO exam_defs (title,title_fr,description,description_fr,type,phase,order_idx) VALUES (@title,@title_fr,@description,@description_fr,@type,@phase,@order_idx)`);
  const run = db.transaction(() => {
    for (const b of [...p1Theory,...p2Theory]) iB.run(b);
    for (const e of [...ghPF,...ghL]) iE.run({...e,category:'ground_handling'});
    for (const e of [...airIF,...airL,...airP2]) iE.run({...e,category:'airborne'});
    for (const e of examDefs) iX.run(e);
  });
  run();
  console.log("Bilingual curriculum seeded");
}

function updateFrenchContent(db) {
  const uB = db.prepare(`UPDATE theory_blocks SET title_fr=@title_fr,description_fr=@description_fr,content_fr=@content_fr WHERE title=@title`);
  const uE = db.prepare(`UPDATE exercises SET title_fr=@title_fr,description_fr=@description_fr WHERE title=@title`);
  const uX = db.prepare(`UPDATE exam_defs SET title_fr=@title_fr,description_fr=@description_fr WHERE title=@title`);
  const run = db.transaction(() => {
    for (const b of [...p1Theory,...p2Theory]) uB.run(b);
    for (const e of [...ghPF,...ghL,...airIF,...airL,...airP2]) uE.run(e);
    for (const e of examDefs) uX.run(e);
  });
  run();
  console.log("French content updated");
}
